#@ load("mysql.lib.yml", "name")

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: #@ name()
  labels:
    app: #@ name()
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
