#@ load("mysql.lib.yml", "name")

apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  annotations:
    kapp.k14s.io/change-group: "scdf.tanzu.vmware.com/db"
  labels:
    app: #@ name()
spec:
  ports:
    - port: 3306
  selector:
    app: #@ name()
