#@ load("kafka.star", "name")
#@ load("kafka.star", "zk_name")
#@ load("kafka.star", "zk_client_name")
#@ load("kafka.star", "zk_server_name")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ zk_server_name()
  labels:
    app: #@ zk_name()
spec:
  ports:
  - name: follower
    port: 2888
  - name: leader
    port: 3888
  clusterIP: None
  selector:
    app: #@ zk_name()
---
apiVersion: v1
kind: Service
metadata:
  name: #@ zk_client_name()
  labels:
    app: #@ zk_name()
spec:
  ports:
  - name: client
    port: 2181
  selector:
    app: #@ zk_name()
