#@ load("kafka.star", "name")
#@ load("kafka.star", "broker_name")
apiVersion: v1
kind: Service
metadata:
  name: #@ broker_name()
  labels:
    app: #@ broker_name()
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: server
  selector:
    app: #@ broker_name()
