#@data/values-schema
---
name: kafka
brokerImage:
  repository: confluentinc/cp-kafka
  tag: 5.5.2
  digest: ""
zkImage:
  repository: confluentinc/cp-zookeeper
  tag: 5.5.2
  digest: ""
registrySecretRef: ""
