#@ load("postgres.lib.yml", "name")
#@ load("postgres.star", "image")
#@ load("postgres.star", "has_image_pull_secrets")
#@ load("postgres.star", "image_pull_secrets")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: #@ image()
        name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: #@ name()
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: #@ name()
        - name: POSTGRES_DB
          value: #@ name()
        ports:
        - containerPort: 5432
          name: #@ name()
      #@ if has_image_pull_secrets():
      imagePullSecrets: #@ image_pull_secrets()
      #@ else:
      imagePullSecrets: [{name: reg-creds}]
      #@ end
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: #@ name()
