FROM bitnami/spring-cloud-dataflow:2.8.2-debian-10-r42
MAINTAINER datav.com

COPY target/spring-cloud-dataflow-server-2.8.4-SNAPSHOT.jar /opt/bitnami/spring-cloud-dataflow/spring-cloud-dataflow-server-2.8.2.jar
