#@ load("rabbitmq.lib.yml", "name")
#@ load("rabbitmq.lib.yml", "username")
#@ load("rabbitmq.lib.yml", "password")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  rabbitmq-user: #@ username()
  rabbitmq-password: #@ password()
