#@ load("prometheus-rsocket-proxy.lib.yml", "name")

apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  ports:
    - name: scrape
      port: 8080
      targetPort: 8080
    - name: rsocket
      port: 7001
      targetPort: 7001
  selector:
    app: #@ name()
