#@ load("prometheus-rsocket-proxy.lib.yml", "name")

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: #@ name()
  labels:
    app: #@ name()
subjects:
  - kind: ServiceAccount
    name: #@ name()
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
