#@ load("prometheus.lib.yml", "name")

apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  labels:
    app: #@ name()
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9090'
spec:
  selector:
    app: #@ name()
  ports:
    - port: 9090
      targetPort: 9090
