#@ load("@ytt:data", "data")
#@ load("skipper.star", "service_spec_type")

apiVersion: v1
kind: Service
metadata:
  name: skipper
  annotations:
    kapp.k14s.io/change-group: "scdf.tanzu.vmware.com/skipper"
    kapp.k14s.io/change-rule: "upsert after upserting scdf.tanzu.vmware.com/db"
  labels:
    app: skipper
    spring-deployment-id: scdf
spec:
  type: #@ service_spec_type()
  ports:
  - port: 80
    targetPort: 7577
  selector:
    app: skipper
