---
apiVersion: v1
kind: Secret
metadata:
  name: reg-creds
  namespace: secrets-ns
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "index.docker.io": {
          "username": "<dockerhub username>",
          "password": "<dockerhub token>",
          "auth": ""
        }
      }
    }

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: reg-creds
  namespace: secrets-ns
spec:
  toNamespaces:
  - "*"
