# control workflow which orchestrates manual milestone builds in
# all dataflow repos, aka one click train build.
name: Milestone Controller

on:
  workflow_dispatch:
    inputs:
      build-zoo-handler:
        description: 'Build Zoo Handler Payload'
        required: false
      build-zoo-handler-properties:
        description: 'Define milestone version as milestone_version=M1'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # initial is when user starts workflow from UI(context is empty)
    # then train build goes through via repos using defined hander rules
    - name: Handle Zoo Control
      uses: jvalkeal/build-zoo-handler@v0.0.4
      with:
        dispatch-handler-token: ${{ secrets.SCDF_ACCESS_TOKEN }}
        dispatch-handler-max: 20
        dispatch-handler-config: >
          [
            {
              "if": "initial == true",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow-build",
                "ref": "2.9.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-dataflow-build' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow-common",
                "ref": "2.9.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-dataflow-common' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-deployer",
                "ref": "2.7.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-deployer' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-deployer-local",
                "ref": "2.7.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-deployer-local' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-deployer-cloudfoundry",
                "ref": "2.7.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-deployer-cloudfoundry' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-deployer-kubernetes",
                "ref": "2.7.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-deployer-kubernetes' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-common-security-config",
                "ref": "1.7.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-common-security-config' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-skipper",
                "ref": "2.8.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-skipper' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow-ui",
                "ref": "3.2.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-dataflow-ui' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow",
                "ref": "2.9.x",
                "workflow": "milestone-worker.yml"
              }
            },
            {
              "if": "data.event == 'build-succeed' && data.repo == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow",
                "ref": "2.9.x",
                "workflow": "promote-milestone.yml"
              }
            },
            {
              "if": "data.event == 'promotion-succeed' && data.repo == 'spring-cloud-dataflow' && data.owner == 'spring-cloud'",
              "action": "workflow_dispatch",
              "workflow_dispatch": {
                "owner": "spring-cloud",
                "repo": "spring-cloud-dataflow",
                "ref": "2.9.x",
                "workflow": "github-release.yml"
              }
            },
            {
              "if": "data.event == 'promotion-failed'",
              "action": "fail",
              "fail": {
                "message": "artifactory promotion failed"
              }
            },
            {
              "if": "data.event == 'ghrelease-failed'",
              "action": "fail",
              "fail": {
                "message": "github release failed"
              }
            },
            {
              "if": "data.event == 'build-failed'",
              "action": "fail",
              "fail": {
                "message": "something went wrong in build train"
              }
            }
          ]
